import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { rules } from "../src/rules/index.ts";

const PHASES = {
	structure: "Structure: the markup of each region",
	paths: "Paths: each `data-prop` resolved to a full path",
	data: "Data: each path looked up in the site's content (needs `--source`)",
} as const;

const lines = [
	"# Rules",
	"",
	"<!-- Generated by `npm run docs` from each rule's metadata. Edit src/rules/<id>/rule.ts instead. -->",
	"",
];

for (const [phase, title] of Object.entries(PHASES)) {
	lines.push(
		`### ${title}`,
		"",
		"| Rule | Severity | Checks |",
		"| --- | --- | --- |",
		...rules
			.filter((rule) => rule.phase === phase)
			.map(
				(rule) =>
					`| [\`${rule.id}\`](#${rule.id}) | ${rule.severity} | ${rule.description} |`,
			),
		"",
	);
}

for (const rule of rules) {
	lines.push(
		`## ${rule.id}`,
		"",
		`**Severity:** ${rule.severity} · **Phase:** ${rule.phase} · **Applies to:** ${
			rule.regionTypes === "*"
				? "every region"
				: rule.regionTypes.length > 0
					? rule.regionTypes.map((type) => `\`${type}\``).join(", ")
					: "the whole page"
		}`,
		"",
		rule.description,
		"",
		rule.rationale,
		"",
		"**Mirrors:**",
		"",
		...rule.sources.map((source) => `- ${source}`),
		"",
		`Fixtures: [src/rules/${rule.id}](src/rules/${rule.id})`,
		"",
	);
}

const out = join(import.meta.dirname, "../RULES.md");
writeFileSync(out, lines.join("\n"));
console.log(`Wrote ${rules.length} rules to RULES.md`);
