import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { rules } from "../src/rules/index.ts";

const lines = [
	"# Rules",
	"",
	"<!-- Generated by `npm run docs` from each rule's metadata. Edit src/rules/<id>/rule.ts instead. -->",
	"",
	"| Rule | Severity | Checks |",
	"| --- | --- | --- |",
	...rules.map(
		(rule) =>
			`| [\`${rule.id}\`](#${rule.id}) | ${rule.severity} | ${rule.description} |`,
	),
	"",
];

for (const rule of rules) {
	lines.push(
		`## ${rule.id}`,
		"",
		`**Severity:** ${rule.severity} · **Applies to:** ${
			rule.regionTypes === "*"
				? "every region"
				: rule.regionTypes.length > 0
					? rule.regionTypes.map((type) => `\`${type}\``).join(", ")
					: "the whole page"
		}`,
		"",
		rule.description,
		"",
		rule.rationale,
		"",
		"**Mirrors:**",
		"",
		...rule.sources.map((source) => `- ${source}`),
		"",
		`Fixtures: [src/rules/${rule.id}](src/rules/${rule.id})`,
		"",
	);
}

const out = join(import.meta.dirname, "../RULES.md");
writeFileSync(out, lines.join("\n"));
console.log(`Wrote ${rules.length} rules to RULES.md`);
